spring:
  application:
    name: Daniel Garcia Test
  h2:
    console.enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:inditex
    username: sa
    password: sa

server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never