openapi: 3.0.3
info:
  title: Inditex Test
  description: |-
    A simple search that returns the current price for branded product:
    - get the current price for a branded product given a search date, product ID and brand ID
  version: 1.0-SNAPSHOT
servers:
  - url: http://localhost:8080/price
tags:
  - name: products
    description: Operations related to products
paths:
  /price:
    get:
      tags:
        - products
      summary: Get current product price information given a search date
      description: Get current product price information given a search date
      operationId: getProductPrice
      parameters:
        - in: query
          name: searchDate
          schema:
            type: string
          description: Represents the date that determines the current price for the branded product. Format YYYY-MM-ddTHH:mm:ss
          example: '2020-06-14T16:00:00'
        - in: query
          name: brandId
          schema:
            type: string
          description: Represents the branded product identification
          example: '1'
        - in: query
          name: productId
          schema:
            type: string
          description: Represents the brand identification
          example: '35455'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceSearchResponseData'
        400:
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        404:
          description: The search returned no results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
components:
  schemas:
    PriceSearchResponseData:
      type: object
      properties:
        brandId:
          type: integer
          example: 1
        productId:
          type: integer
          example: 35455
        priority:
          type: integer
          example: 2
        startDate:
          type: string
          example: '2020-06-14 16:00:00'
        endDate:
          type: string
          example: '2020-06-14 16:00:00'
        price:
          type: number
          example: 50.45
    ValidationError:
      type: object
      properties:
        message:
          type: string
          example: 'The brand ID is required'
    NotFoundError:
      type: object
      properties:
        message:
          type: string
          example: 'The search date has not returned any register'